name: traffic_violations_app
description: Traffic violations management and analytics system for drivers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_messaging:
  provider:
  intl:
  flutter_localizations:
    sdk: flutter
  fl_chart:
  pdf:
  printing:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - lib/core/localization/strings_en.arb
    - lib/core/localization/strings_ar.arb
